document.addEventListener("DOMContentLoaded",
    function(){
        //Rendernskills
        renderSkills();
        initModal();
        initContactValidation();
        initThemeToggle();
        renderprojects();
        renderexperience();
        projectsfilter();
        updateScrollProgress();
        renderProjects();
        initBackToTop();
        initDynamicGreeting();
        initProjectCount();
    }
)